<a href="https://colab.research.google.com/github/rashmi2383/Machine-learning/blob/main/MNIST_sigmoid.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tensorflow keras numpy mnist matplotlib

In [5]:
#import the packages/dependencies
import numpy as np
import mnist #get dataset from
import matplotlib.pyplot as plt #Graph
from keras.models import Sequential   #ANN
from keras.layers import Dense #The layers in the ANN
from keras.layers import Conv2D, MaxPool2D, Flatten, ZeroPadding2D, Activation
from keras.utils  import to_categorical

#load the dataset
train_images = mnist.train_images()  #training data images
train_labels = mnist.train_labels()  #training data labels
test_images = mnist.test_images()    #training data images
test_labels = mnist.test_labels()    #training data labels

#Normalizing the images. Normalize the pixel values from [0,255] to [-0.5,0.5] to make our network easier to train
train_images = (train_images/255)  
test_images = (test_images/255)
#Flattening the images. Flatten each 28x28 image into a 784 dimensional vector to pass into the neural network
train_images = train_images.reshape((-1,28,28,1))
test_images = test_images.reshape((-1,28,28,1))
#print the shape of our images
print(train_images.shape)  #60,000 rows and 784 columns
print(test_images.shape)   #10,000 rows and 784 columns

#Build the model
#3 layers
model2 = Sequential()
model2.add(ZeroPadding2D(padding=((1,0),(1,0))))
model2.add(Conv2D(5,kernel_size=(5,5),strides=(2,2),input_shape=train_images.shape[1:]))
model2.add(Activation('relu'))
model2.add(Dense(100))
#model2.add(MaxPool2D(pool_size=(3,3),strides=1))
#model2.add(Activation('relu')) 
model2.add(Flatten())                #model.add(Dense(64, activation='relu'))
model2.add(Dense(10,activation='sigmoid'))

#compile the model
#The loss function measures how well the model did on training and then tries to improve on it using the optimizer
model2.compile(
    optimizer='adam',
    loss = 'categorical_crossentropy', #(class that are greater than 2)
    metrics = ['accuracy']
)

#train the model
model2.fit(
    train_images,
    to_categorical(train_labels),                 #Ex. 2 it expects [0,0,1,0,0,0,0,0,0,0] 
    epochs=20,                        #the number of iterations over the entire dataset to train on
    batch_size=32,                   #number of samples per gradient update for training
    validation_split=0.2
)
model2.summary()

(60000, 28, 28, 1)
(10000, 28, 28, 1)
Epoch 1/20
1500/1500 [==============================] - 5s 3ms/step - loss: 0.4117 - accuracy: 0.8802 - val_loss: 0.1190 - val_accuracy: 0.9636
Epoch 2/20
1500/1500 [==============================] - 4s 3ms/step - loss: 0.1053 - accuracy: 0.9687 - val_loss: 0.0929 - val_accuracy: 0.9722
Epoch 3/20
1500/1500 [==============================] - 4s 3ms/step - loss: 0.0805 - accuracy: 0.9743 - val_loss: 0.0863 - val_accuracy: 0.9743
Epoch 4/20
1500/1500 [==============================] - 4s 3ms/step - loss: 0.0714 - accuracy: 0.9780 - val_loss: 0.0923 - val_accuracy: 0.9718
Epoch 5/20
1500/1500 [==============================] - 4s 3ms/step - loss: 0.0613 - accuracy: 0.9805 - val_loss: 0.0879 - val_accuracy: 0.9747
Epoch 6/20
1500/1500 [==============================] - 4s 3ms/step - loss: 0.0566 - accuracy: 0.9826 - val_loss: 0.0881 - val_accuracy: 0.9763
Epoch 7/20
1500/1500 [==============================] - 4s 3ms/step - loss: 0.0553 - accuracy: 0.9

In [6]:
model2.layers[1].output

#Evaluate the model
model2.evaluate(
    test_images,
    to_categorical(test_labels)
)

#Save the model
model2.save_weights('model2.h5')

#predict on the first 5 test images
predictions = model2.predict(test_images[:6])
#print our model's prediction 
print(np.argmax(predictions, axis=1))
print(test_labels[:6])

print(model2.weights)
np.save('model2.npy',model2.get_weights())

print(model2.layers[1].get_weights()[0])
#print(model.layers[1].get_weights()[1])

print(model2.layers[0].get_config())

print(model2.layers[1].get_config())

print(model2.layers[2].get_config())

print(model2.layers[3].get_config())

print(model2.layers[4].get_config())

print(model2.layers[5].get_config())

313/313 [==============================] - 1s 3ms/step - loss: 0.0912 - accuracy: 0.9771
[7 2 1 0 4 1]
[7 2 1 0 4 1]
[<tf.Variable 'conv2d_2/kernel:0' shape=(5, 5, 1, 5) dtype=float32, numpy=
array([[[[ 0.01848824, -0.2869611 ,  0.09377609,  0.16203804,
           0.1786631 ]],

        [[-0.00926721, -0.22012086,  0.1093236 ,  0.17964013,
          -0.13487953]],

        [[-0.3179518 , -0.2870587 ,  0.00460908, -0.279157  ,
          -0.07699841]],

        [[-0.21497494, -0.32558495, -0.26013258, -0.2495632 ,
          -0.02049723]],

        [[ 0.01364908, -0.2111339 , -0.17128448, -0.23359418,
           0.1410223 ]]],


       [[[ 0.1088592 , -0.10952226,  0.0721378 ,  0.03807976,
          -0.07877985]],

        [[ 0.16935068, -0.26242438,  0.19928274,  0.21705064,
           0.17067726]],

        [[-0.4642618 , -0.28045076, -0.04958932, -0.01231184,
           0.1146315 ]],

        [[-0.50522256, -0.20609953,  0.20306972, -0.22163472,
          -0.19374454]],

        [[-0.2

/usr/local/lib/python3.6/dist-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)
