<a href="https://colab.research.google.com/github/rashmi2383/Machine-learning/blob/main/MNIST.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Description: This program classifies the MNIST handwritten digit images as a number  0 - 9
!pip install tensorflow keras numpy mnist matplotlib



In [37]:
#import the packages/dependencies
import numpy as np
import mnist #get dataset from
import matplotlib.pyplot as plt #Graph
from keras.models import Sequential   #ANN
from keras.layers import Dense #The layers in the ANN
from keras.layers import Conv2D, MaxPool2D, Flatten, ZeroPadding2D, Activation
from keras.utils  import to_categorical

In [38]:
#load the dataset
train_images = mnist.train_images()  #training data images
train_labels = mnist.train_labels()  #training data labels
test_images = mnist.test_images()    #training data images
test_labels = mnist.test_labels()    #training data labels 

In [40]:
#Normalizing the images. Normalize the pixel values from [0,255] to [-0.5,0.5] to make our network easier to train
train_images = (train_images/255)  
test_images = (test_images/255)
#Flattening the images. Flatten each 28x28 image into a 784 dimensional vector to pass into the neural network
#train_images = train_images.reshape((-1,784))
#test_images = test_images.reshape((-1,784))
train_images = train_images.reshape((-1,28,28,1))
test_images = test_images.reshape((-1,28,28,1))
#print the shape of our images
print(train_images.shape)  #60,000 rows and 784 columns
print(test_images.shape)   #10,000 rows and 784 columns 

(60000, 28, 28, 1)
(10000, 28, 28, 1)


In [52]:
#Build the model
#3 layers, 2 layers with 64 neurons and the relu function, 1 layer with 10 neurons and softmax function
model = Sequential()
model.add(ZeroPadding2D(padding=((1,0),(1,0))))
#model.add(Dense(64, activation='relu',input_dim=784))
model.add(Conv2D(5,kernel_size=(5,5),strides=(2,2),input_shape=train_images.shape[1:]))
model.add(Activation('relu'))
model.add(MaxPool2D(pool_size=(3,3),strides=1)) 
#model.add(Activation('relu'))
model.add(Flatten())                #model.add(Dense(64, activation='relu'))
model.add(Dense(10,activation='softmax'))

In [53]:
#compile the model
#The loss function measures how well the model did on training and then tries to improve on it using the optimizer
model.compile(
    optimizer='adam',
    loss = 'categorical_crossentropy', #(class that are greater than 2)
    metrics = ['accuracy']
)

In [17]:
train_images.shape[1:]

(28, 28, 1)

In [9]:
to_categorical(train_labels).shape

(60000, 10)

In [63]:
#train the model
model.fit(
    train_images,
    to_categorical(train_labels),                 #Ex. 2 it expects [0,0,1,0,0,0,0,0,0,0] 
    epochs=20,                        #the number of iterations over the entire dataset to train on
    batch_size=32,                   #number of samples per gradient update for training
    validation_split=0.2
)
model.summary()

Epoch 1/20
1500/1500 [==============================] - 4s 3ms/step - loss: 0.0540 - accuracy: 0.9833 - val_loss: 0.0765 - val_accuracy: 0.9787
Epoch 2/20
1500/1500 [==============================] - 4s 2ms/step - loss: 0.0536 - accuracy: 0.9839 - val_loss: 0.0759 - val_accuracy: 0.9781
Epoch 3/20
1500/1500 [==============================] - 4s 2ms/step - loss: 0.0535 - accuracy: 0.9833 - val_loss: 0.0760 - val_accuracy: 0.9790
Epoch 4/20
1500/1500 [==============================] - 4s 2ms/step - loss: 0.0536 - accuracy: 0.9829 - val_loss: 0.0757 - val_accuracy: 0.9779
Epoch 5/20
1500/1500 [==============================] - 4s 2ms/step - loss: 0.0533 - accuracy: 0.9835 - val_loss: 0.0777 - val_accuracy: 0.9772
Epoch 6/20
1500/1500 [==============================] - 3s 2ms/step - loss: 0.0533 - accuracy: 0.9836 - val_loss: 0.0756 - val_accuracy: 0.9782
Epoch 7/20
1500/1500 [==============================] - 4s 2ms/step - loss: 0.0526 - accuracy: 0.9841 - val_loss: 0.0762 - val_accuracy:

In [17]:
model.layers[1].output

<KerasTensor: shape=(None, 13, 13, 5) dtype=float32 (created by layer 'conv2d_3')>

In [68]:
#Evaluate the model
model.evaluate(
    test_images,
    to_categorical(test_labels)
)

313/313 [==============================] - 1s 2ms/step - loss: 0.0666 - accuracy: 0.9786


[0.06662221997976303, 0.978600025177002]

In [69]:
#Save the model
model.save_weights('model.h5')

In [70]:
#predict on the first 5 test images
predictions = model.predict(test_images[:6])
#print our model's prediction 
print(np.argmax(predictions, axis=1))
print(test_labels[:6])

[7 2 1 0 4 1]
[7 2 1 0 4 1]


In [ ]:
for i in range(0,6):
  first_image = test_images[i]
  first_image = np.array(first_image, dtype='float')
  pixels = first_image.reshape((28,28))
  plt.imshow(pixels, cmap='gray')
  plt.show()

In [72]:
print(model.weights)
np.save('model.npy',model.get_weights())

[<tf.Variable 'conv2d_9/kernel:0' shape=(5, 5, 1, 5) dtype=float32, numpy=
array([[[[ 1.48988886e+01,  2.25969386e+00,  1.60941988e-01,
          -6.55490255e+00,  5.09958975e-02]],

        [[ 1.16164579e+01, -7.81081855e-01, -1.79316271e-02,
           3.40973163e+00,  1.51382089e-01]],

        [[ 5.16546249e+00, -2.26924491e+00,  9.78401303e-02,
           1.51229506e+01, -6.88023807e-04]],

        [[-2.16462421e+00,  3.21288034e-02,  7.30890408e-02,
           1.65534954e+01, -1.39797851e-01]],

        [[-9.00408363e+00,  1.89344609e+00, -5.84464744e-02,
           1.96979027e+01,  4.30291705e-02]]],


       [[[ 7.26722765e+00,  1.20582609e+01, -1.39201030e-01,
          -5.53431797e+00,  5.90908974e-02]],

        [[ 1.37334042e+01,  8.34181023e+00,  1.40622869e-01,
           5.89895201e+00,  1.23221420e-01]],

        [[ 1.07049217e+01,  8.86701965e+00, -6.45360723e-02,
           1.23417082e+01, -1.01674266e-01]],

        [[-7.76448171e-04,  8.99938679e+00,  3.01802550e-02

/usr/local/lib/python3.6/dist-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)


In [71]:
print(model.layers[1].get_weights()[0])
#print(model.layers[1].get_weights()[1])

[[[[ 1.48988886e+01  2.25969386e+00  1.60941988e-01 -6.55490255e+00
     5.09958975e-02]]

  [[ 1.16164579e+01 -7.81081855e-01 -1.79316271e-02  3.40973163e+00
     1.51382089e-01]]

  [[ 5.16546249e+00 -2.26924491e+00  9.78401303e-02  1.51229506e+01
    -6.88023807e-04]]

  [[-2.16462421e+00  3.21288034e-02  7.30890408e-02  1.65534954e+01
    -1.39797851e-01]]

  [[-9.00408363e+00  1.89344609e+00 -5.84464744e-02  1.96979027e+01
     4.30291705e-02]]]


 [[[ 7.26722765e+00  1.20582609e+01 -1.39201030e-01 -5.53431797e+00
     5.90908974e-02]]

  [[ 1.37334042e+01  8.34181023e+00  1.40622869e-01  5.89895201e+00
     1.23221420e-01]]

  [[ 1.07049217e+01  8.86701965e+00 -6.45360723e-02  1.23417082e+01
    -1.01674266e-01]]

  [[-7.76448171e-04  8.99938679e+00  3.01802550e-02  1.37219372e+01
    -1.27481762e-02]]

  [[-1.14109278e+01  1.18958645e+01 -3.27373073e-02  6.41696787e+00
    -8.26975927e-02]]]


 [[[-9.56999123e-01  1.51639919e+01  7.12837949e-02 -1.51923585e+00
    -9.51917395e-0

In [29]:
print(model.layers[0].get_config())

{'name': 'zero_padding2d_3', 'trainable': True, 'dtype': 'float32', 'padding': ((1, 0), (1, 0)), 'data_format': 'channels_last'}


In [30]:
print(model.layers[1].get_config())

{'name': 'conv2d_3', 'trainable': True, 'batch_input_shape': (None, 28, 28, 1), 'dtype': 'float32', 'filters': 5, 'kernel_size': (5, 5), 'strides': (2, 2), 'padding': 'valid', 'data_format': 'channels_last', 'dilation_rate': (1, 1), 'groups': 1, 'activation': 'linear', 'use_bias': True, 'kernel_initializer': {'class_name': 'GlorotUniform', 'config': {'seed': None}}, 'bias_initializer': {'class_name': 'Zeros', 'config': {}}, 'kernel_regularizer': None, 'bias_regularizer': None, 'activity_regularizer': None, 'kernel_constraint': None, 'bias_constraint': None}


In [31]:
print(model.layers[2].get_config())

{'name': 'activation_3', 'trainable': True, 'dtype': 'float32', 'activation': 'relu'}


In [32]:
print(model.layers[3].get_config())

{'name': 'max_pooling2d_3', 'trainable': True, 'dtype': 'float32', 'pool_size': (3, 3), 'padding': 'valid', 'strides': (1, 1), 'data_format': 'channels_last'}


In [33]:
print(model.layers[4].get_config())

{'name': 'flatten_3', 'trainable': True, 'dtype': 'float32', 'data_format': 'channels_last'}


In [34]:
print(model.layers[5].get_config())

{'name': 'dense_3', 'trainable': True, 'dtype': 'float32', 'units': 10, 'activation': 'softmax', 'use_bias': True, 'kernel_initializer': {'class_name': 'GlorotUniform', 'config': {'seed': None}}, 'bias_initializer': {'class_name': 'Zeros', 'config': {}}, 'kernel_regularizer': None, 'bias_regularizer': None, 'activity_regularizer': None, 'kernel_constraint': None, 'bias_constraint': None}
