<a href="https://colab.research.google.com/github/rashmi2383/Machine-learning/blob/main/mnist_dense.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tensorflow keras numpy mnist matplotlib

In [4]:
#import the packages/dependencies
import tensorflow as tf
import numpy as np
import mnist #get dataset from
import matplotlib.pyplot as plt #Graph
from keras.models import Sequential   #ANN
from keras.layers import Dense #The layers in the ANN
from keras.layers import Conv2D, MaxPool2D, Flatten, ZeroPadding2D, Activation, Dropout
from keras.utils  import to_categorical 

#load the dataset
train_images = mnist.train_images()  #training data images
train_labels = mnist.train_labels()  #training data labels
test_images = mnist.test_images()    #training data images
test_labels = mnist.test_labels()    #training data labels 
#Normalizing the images. Normalize the pixel values from [0,255] to [-0.5,0.5] to make our network easier to train
train_images = (train_images/255)  
test_images = (test_images/255)
#Flattening the images. Flatten each 28x28 image into a 784 dimensional vector to pass into the neural network
train_images = train_images.reshape((-1,784))
test_images = test_images.reshape((-1,784))
#print the shape of our images
print(train_images.shape)  #60,000 rows and 784 columns
print(test_images.shape)   #10,000 rows and 784 columns

(60000, 784)
(10000, 784)


In [45]:
#Build the model
#3 layers, 2 layers with 64 neurons and the relu function, 1 layer with 10 neurons and softmax function
model1 = Sequential()
model1.add(Dense(64, activation='relu',input_dim=784))
#model.add(Dropout(0.2))
#model.add(MaxPool2D(pool_size=(3,3),strides=1)) 
#model.add(Dense(64, activation='relu'))
model1.add(Dense(10,activation='softmax'))

In [47]:
model1.compile(
    optimizer='adam',
    loss = 'categorical_crossentropy',
    metrics=['accuracy']
)

In [48]:
#train the model
model1.fit(
    train_images,
    to_categorical(train_labels),                 #Ex. 2 it expects [0,0,1,0,0,0,0,0,0,0] 
    epochs=10,                        #the number of iterations over the entire dataset to train on
    batch_size=32,                   #number of samples per gradient update for training
)
model.summary()

Epoch 1/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.5101 - accuracy: 0.8607
Epoch 2/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1578 - accuracy: 0.9540
Epoch 3/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1056 - accuracy: 0.9682
Epoch 4/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0813 - accuracy: 0.9752
Epoch 5/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0651 - accuracy: 0.9802
Epoch 6/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0555 - accuracy: 0.9830
Epoch 7/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0443 - accuracy: 0.9866
Epoch 8/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0393 - accuracy: 0.9883
Epoch 9/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0333 - accuracy: 0.9899
Epoch 10/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.028

In [49]:
#Evaluate the model
model1.evaluate(
    test_images,
    to_categorical(test_labels)
)

313/313 [==============================] - 0s 1ms/step - loss: 0.0878 - accuracy: 0.9751


[0.08784414827823639, 0.9750999808311462]

In [52]:
#Save the model
model1.save_weights('model1_weights.h5')

In [53]:
#predict on the first 5 test images
predictions = model1.predict(test_images[:6])
#print our model's prediction 
print(np.argmax(predictions, axis=1))
print(test_labels[:6])

[7 2 1 0 4 1]
[7 2 1 0 4 1]


In [54]:
print(model.weights)
np.save('model1.npy',model1.get_weights())

[<tf.Variable 'dense_14/kernel:0' shape=(784, 64) dtype=float32, numpy=
array([[-0.06161778,  0.04665623, -0.04415177, ...,  0.04895928,
         0.02045633, -0.02782877],
       [ 0.0040929 , -0.0644649 , -0.04462207, ..., -0.0775734 ,
        -0.05806854, -0.07683758],
       [-0.08111202, -0.02771279, -0.076168  , ...,  0.01335197,
         0.0443865 , -0.01163987],
       ...,
       [-0.06370263,  0.04204104,  0.00605796, ..., -0.00184452,
        -0.08209976,  0.03478918],
       [ 0.03389598, -0.06862841,  0.01266048, ..., -0.02678891,
         0.0003591 , -0.01773597],
       [ 0.02211143,  0.02661365, -0.03863011, ..., -0.02201575,
        -0.06180966, -0.0168872 ]], dtype=float32)>, <tf.Variable 'dense_14/bias:0' shape=(64,) dtype=float32, numpy=
array([ 0.07075786, -0.03919408,  0.10103785, -0.05249879,  0.0016029 ,
       -0.02512585, -0.02169934,  0.02113495,  0.12718444,  0.01028848,
        0.16867693,  0.00277754,  0.16535357,  0.02597526,  0.11345256,
       -0.0688923

/usr/local/lib/python3.6/dist-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)
